/teleop_turtle:
  ros__parameters:
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    scale_angular: 2.0
    scale_linear: 4.0
    use_sim_time: false

